### ===== DESAFIO 01 - COMISSÕES =====
POST http://localhost:5297/api/comissoes/calcular
Content-Type: application/json

{
  "vendas": [
    { "vendedor": "João Silva", "valor": 1200.50 },
    { "vendedor": "João Silva", "valor": 250.30 },
    { "vendedor": "Maria Souza", "valor": 800.00 },
    { "vendedor": "Maria Souza", "valor": 75.00 }
  ]
}

### ===== DESAFIO 02 - ESTOQUE =====
### Teste Estoque - Obter produtos
GET http://localhost:5297/api/estoque/produtos

### Teste Estoque - Entrada
POST http://localhost:5297/api/estoque/movimentar
Content-Type: application/json

{
  "codigoProduto": 101,
  "descricao": "Compra de canetas",
  "quantidade": 50,
  "tipoMovimentacao": "ENTRADA"
}

### Teste Estoque - Saída
POST http://localhost:5297/api/estoque/movimentar
Content-Type: application/json

{
  "codigoProduto": 101,
  "descricao": "Venda para cliente",
  "quantidade": 50,
  "tipoMovimentacao": "SAIDA"
}

### ===== DESAFIO 03 - RELATÓRIO DE VENDAS =====
### ===== JUROS =====
POST http://localhost:5297/api/juros/calcular
Content-Type: application/json

{
  "valorOriginal": 1000.00,
  "dataVencimento": "2025-11-20"
}

### ===== DATA FUTURA =====
POST http://localhost:5297/api/juros/calcular
Content-Type: application/json

{
  "valorOriginal": 1000.00,
  "dataVencimento": "2025-12-25"
}